### ISSUE TITLE
Allow generation on specific controller

### ISSUE THREAD

**Issue by BennyM** [Smartasses/RequestHandlers.Mvc#5]
When using swagger to generate documentation for your api everything is now grouped under Proxy. It would be better if we had control over that so we can group related requesthandlers together.

**Comment by glenndierckx** [comment]
Sample for swagger:

`c.OperationFilter<SwaggerCustomDocumentationOperationFilter>();`

`    public class SwaggerCustomDocumentationOperationFilter : IOperationFilter
    {
        public void Apply(Operation operation, OperationFilterContext context)
        {
            var attr = context.ApiDescription.ActionAttributes().OfType<ApiDescriptionAttribute>().FirstOrDefault();
            if (attr != null)
            {
                operation.Description = attr.Description;
                operation.Tags = new List<string> {attr.OperationGroupName};
            }
        }
    }`

`
    public class ApiDescriptionAttribute : Attribute
    {
        public string Description { get; }
        public string OperationGroupName { get; }

        public ApiDescriptionAttribute(string operationGroupName, string description)
        {
            OperationGroupName = operationGroupName;
            Description = description;
        }
    }`
